name: CI
on: 
  push:
    branches: [master, main]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: 'check --fix'
      
      - name: Check formatting with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'
